// flow-typed signature: 6d7dabff73075dc26bc15d68ad3a8fbb
// flow-typed version: <<STUB>>/errorjs_v^0.4.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'errorjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'errorjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'errorjs/dist/error' {
  declare module.exports: any;
}

declare module 'errorjs/dist/errors' {
  declare module.exports: any;
}

declare module 'errorjs/dist/factory' {
  declare module.exports: any;
}

declare module 'errorjs/dist/index' {
  declare module.exports: any;
}

declare module 'errorjs/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'errorjs/flow-typed/npm/babel-plugin-transform-flow-comments_vx.x.x' {
  declare module.exports: any;
}

declare module 'errorjs/flow-typed/npm/chai_v3.5.x' {
  declare module.exports: any;
}

declare module 'errorjs/flow-typed/npm/documentation_vx.x.x' {
  declare module.exports: any;
}

declare module 'errorjs/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'errorjs/flow-typed/npm/eslint-config-xo_vx.x.x' {
  declare module.exports: any;
}

declare module 'errorjs/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module 'errorjs/flow-typed/npm/eslint-plugin-mocha_vx.x.x' {
  declare module.exports: any;
}

declare module 'errorjs/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'errorjs/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module 'errorjs/flow-typed/npm/mocha_v3.1.x' {
  declare module.exports: any;
}

declare module 'errorjs/lib/error' {
  declare module.exports: any;
}

declare module 'errorjs/lib/errors' {
  declare module.exports: any;
}

declare module 'errorjs/lib/factory' {
  declare module.exports: any;
}

declare module 'errorjs/lib/index' {
  declare module.exports: any;
}

declare module 'errorjs/test/error' {
  declare module.exports: any;
}

declare module 'errorjs/test/factory' {
  declare module.exports: any;
}

// Filename aliases
declare module 'errorjs/dist/error.js' {
  declare module.exports: $Exports<'errorjs/dist/error'>;
}
declare module 'errorjs/dist/errors.js' {
  declare module.exports: $Exports<'errorjs/dist/errors'>;
}
declare module 'errorjs/dist/factory.js' {
  declare module.exports: $Exports<'errorjs/dist/factory'>;
}
declare module 'errorjs/dist/index.js' {
  declare module.exports: $Exports<'errorjs/dist/index'>;
}
declare module 'errorjs/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'errorjs/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'errorjs/flow-typed/npm/babel-plugin-transform-flow-comments_vx.x.x.js' {
  declare module.exports: $Exports<'errorjs/flow-typed/npm/babel-plugin-transform-flow-comments_vx.x.x'>;
}
declare module 'errorjs/flow-typed/npm/chai_v3.5.x.js' {
  declare module.exports: $Exports<'errorjs/flow-typed/npm/chai_v3.5.x'>;
}
declare module 'errorjs/flow-typed/npm/documentation_vx.x.x.js' {
  declare module.exports: $Exports<'errorjs/flow-typed/npm/documentation_vx.x.x'>;
}
declare module 'errorjs/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'errorjs/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'errorjs/flow-typed/npm/eslint-config-xo_vx.x.x.js' {
  declare module.exports: $Exports<'errorjs/flow-typed/npm/eslint-config-xo_vx.x.x'>;
}
declare module 'errorjs/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'errorjs/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module 'errorjs/flow-typed/npm/eslint-plugin-mocha_vx.x.x.js' {
  declare module.exports: $Exports<'errorjs/flow-typed/npm/eslint-plugin-mocha_vx.x.x'>;
}
declare module 'errorjs/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'errorjs/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'errorjs/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'errorjs/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module 'errorjs/flow-typed/npm/mocha_v3.1.x.js' {
  declare module.exports: $Exports<'errorjs/flow-typed/npm/mocha_v3.1.x'>;
}
declare module 'errorjs/lib/error.js' {
  declare module.exports: $Exports<'errorjs/lib/error'>;
}
declare module 'errorjs/lib/errors.js' {
  declare module.exports: $Exports<'errorjs/lib/errors'>;
}
declare module 'errorjs/lib/factory.js' {
  declare module.exports: $Exports<'errorjs/lib/factory'>;
}
declare module 'errorjs/lib/index.js' {
  declare module.exports: $Exports<'errorjs/lib/index'>;
}
declare module 'errorjs/test/error.js' {
  declare module.exports: $Exports<'errorjs/test/error'>;
}
declare module 'errorjs/test/factory.js' {
  declare module.exports: $Exports<'errorjs/test/factory'>;
}
